name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:fix

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          npx
          -p @semantic-release/changelog
          -p @semantic-release/git
          -p @semantic-release/github
          -p @semantic-release/release-notes-generator
          -p semantic-release
          semantic-release
