name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    environment: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: |
          npm install -g corepack@latest
          corepack enable

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          pnpm
          --package="conventional-changelog-conventionalcommits@6"
          --package="@semantic-release/changelog"
          --package="@semantic-release/git"
          --package="@semantic-release/github"
          --package="@semantic-release/release-notes-generator"
          --package="semantic-release@21"
          dlx semantic-release
